### ISSUE TITLE
Module src/redisearch.so failed to load: src/redisearch.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CrimsonTide0** [RediSearch/RediSearch#1792]
The redisearch.so file seems to be missing from the RediSearch/src directory in this git. Please fix this so that I can use redisearch.

**Comment by CrimsonTide0** [comment]
I downloaded redisearch.so from somewhere else and it seems to work, but when I change the config file of the redis-server (the service that runs when the computer is booted) it can't seem to use the module and becomes inactive when trying to start it. I know the pathing is right so what's the issue? When I manually run RediSearch with make run it runs fine now that I inserted the redisearch.so file, but when I change the config file of the service it doesn't work.

**Comment by gkorland** [comment]
Which version of Redis are you using? Please notice the latest RediSearch requires Redis 6.0.8+

**Comment by CrimsonTide0** [comment]
I followed this guide: https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-18-04
Apparently, it should install the latest version of Redis. As for RediSearch, I built it from source using the official documentation: https://oss.redislabs.com/redisearch/Quick_Start/
Ironically the official documentation installs Redis 5.0.7 and not the latest release. Perhaps the redisearch.so file I found from the internet is also an older version and is more compatible with 5.0.7 and can't be run from the latest version of Redis.

**Comment by CrimsonTide0** [comment]
Hi, I fixed the issue by simply moving my .so file into /etc/redis. Perhaps the pathing is weird when you use ~ or it needs permission accessing root folders.

**Comment by Jonarod** [comment]
This is still an issue for me with relative paths like `./redisearch.so`, it just can't seem to find it, I need to force absolute paths like `/usr/local/redis/redisearch.so`

**Comment by Jonarod** [comment]
Ok I think I figured it out...
For some reasons it seems like modules are loaded relative to the `data` path, in my case in my `redis.conf` I set a custom `data` path to `../data` so I had to specify the module path like this: `../relative/path/to/redisearch.so`. When I set the `data` parameter to be `./data`, I need to change the module path accordingly to `./redisearch.so`.
