### ISSUE TITLE
MOD-4830: Numeric range aggregation with cursor causes segmentation fault

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [RediSearch/RediSearch#3535]
Because of #3364 we are using [redis-stack 6.2.4-v3](https://hub.docker.com/layers/redis/redis-stack/6.2.4-v3/images/sha256-aeeb3cf95fdc063f824084f7a11475daacfa3fedc1b461147c3c3d59103fdfcc?context=explore), but in this version we are causing shutdown of the container because of segmentation faults.

The bug occurs in a situation like this:
- We have an index for JSON documents with numeric fields
- We update the JSON documents regularly
- We perform aggregation on the documents with cursor.

In order to reproduce the case I have prepared a C# application which opens up a connection to `localhost:6379` and creates an index for a document like this `{ "Tag": "A", "Number": 0.3124576 }`. Then spawns up two tasks
1- Uploads `32` documents at a time via batching.
2- Runs basic aggregation with query `@\$\.Number:[-inf,0.5]` and with cursor count `16`
  - `16` (at least half of batch size) is intentional to make it continue iterating while uploading faster.

I spin up containers like this `docker container run --name myredis -p 6379:6379 -d redis/redis-stack:6.2.4-v3` then run `docker stats` to watch whether the container is alive or shut down.

Running the application almost immediately causes the redis container to crash.

Here are the container logs (contains copy paste information)
[RedisNumericCrash-ContainerLogs-230418.txt](https://github.com/RediSearch/RediSearch/files/11263450/RedisNumericCrash-ContainerLogs-230418.txt)

And the application code for reproduction of the case
[RedisNumericCrashRepro-230418.zip](https://github.com/RediSearch/RediSearch/files/11263452/RedisNumericCrashRepro-230418.zip)

Here is the copy-paste excerpt of the crash log
```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
9:M 18 Apr 2023 14:49:58.930 # Redis 6.2.7 crashed by signal: 11, si_code: 128
9:M 18 Apr 2023 14:49:58.930 # Accessing address: (nil)
9:M 18 Apr 2023 14:49:58.930 # Crashed running the instruction at: 0x7f0da56db5a3

------ STACK TRACE ------
EIP:
/opt/redis-stack/lib/redisearch.so(+0x1355a3)[0x7f0da56db5a3]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f0da6486420]
/opt/redis-stack/lib/redisearch.so(+0x1355a3)[0x7f0da56db5a3]
/opt/redis-stack/lib/redisearch.so(IR_Read+0x40)[0x7f0da56db1b0]
/opt/redis-stack/lib/redisearch.so(+0x12ed13)[0x7f0da56d4d13]
/opt/redis-stack/lib/redisearch.so(+0x152446)[0x7f0da56f8446]
/opt/redis-stack/lib/redisearch.so(sendChunk+0x303)[0x7f0da56a47e3]
/opt/redis-stack/lib/redisearch.so(+0xfeaa0)[0x7f0da56a4aa0]
/opt/redis-stack/lib/redisearch.so(RSCursorCommand+0x18a)[0x7f0da56a535a]
/opt/redis-stack/bin/redis-server *:6379(RedisModuleCommandDispatcher+0x67)[0x55fcb570af67]
/opt/redis-stack/bin/redis-server *:6379(call+0xf0)[0x55fcb567c860]
/opt/redis-stack/bin/redis-server *:6379(processCommand+0x643)[0x55fcb567e593]
/opt/redis-stack/bin/redis-server *:6379(processCommandAndResetClient+0x20)[0x55fcb5691b40]
/opt/redis-stack/bin/redis-server *:6379(processInputBuffer+0xea)[0x55fcb569449a]
/opt/redis-stack/bin/redis-server *:6379(+0x10119c)[0x55fcb572d19c]
/opt/redis-stack/bin/redis-server *:6379(aeProcessEvents+0x2ca)[0x55fcb5674e2a]
/opt/redis-stack/bin/redis-server *:6379(aeMain+0x1d)[0x55fcb56750bd]
/opt/redis-stack/bin/redis-server *:6379(main+0x33a)[0x55fcb56714ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f0da62a4083]
/opt/redis-stack/bin/redis-server *:6379(_start+0x2e)[0x55fcb56719ce]

------ REGISTERS ------
9:M 18 Apr 2023 14:49:58.931 # 
RAX:0000000000000172 RBX:00007f0da5e36788
RCX:00007f0da5e25030 RDX:342d626335372d37
RDI:00007f0da5e36788 RSI:00007f0da5e367b0
RBP:00007f0da5e25030 RSP:00007ffd1397b640
R8 :0000000000000080 R9 :0000000000000004
R10:00007ffd1397b6e0 R11:0000000000000008
R12:00007f0da56dadc0 R13:00007f0da5e367b0
R14:00007f0da5fac200 R15:0000000000000001
RIP:00007f0da56db5a3 EFL:0000000000010202
CSGSFS:002b000000000033
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b64f) -> 00000003b5708bec
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b64e) -> 00007ffd1397b920
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b64d) -> 00007f0da56d4d13
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b64c) -> 0000000000000001
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b64b) -> 00007f0da5e43700
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b64a) -> 00007ffd1397b6e0
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b649) -> 00007f0da56db1b0
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b648) -> 0000000000000001
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b647) -> 00007f0da5fac200
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b646) -> 0000000000000001
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b645) -> 00007f0da56dadc0
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b644) -> 00007ffd1397b6e0
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b643) -> 00007f0da5e36780
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b642) -> 00007f0da5e25030
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b641) -> a2e3e80bb8afef00
9:M 18 Apr 2023 14:49:58.931 # (00007ffd1397b640) -> 0000000100000001

------ INFO OUTPUT ------
# Server
redis_version:6.2.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:adcdff4a0d295794
redis_mode:standalone
os:Linux 5.10.102.1-microsoft-standard-WSL2 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:9.4.0
process_id:9
process_supervised:no
run_id:08adfa1d2b100370cd9130b745bd15308328ace6
tcp_port:6379
server_time_usec:1681829398930486
uptime_in_seconds:30
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:4107798
executable:/opt/redis-stack/bin/redis-server
config_file:
io_threads_active:0

# Clients
connected_clients:2
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:72
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:1587880
used_memory_human:1.51M
used_memory_rss:22740992
used_memory_rss_human:21.69M
used_memory_peak:1587880
used_memory_peak_human:1.51M
used_memory_peak_perc:101.43%
used_memory_overhead:1081640
used_memory_startup:1006536
used_memory_dataset:506240
used_memory_dataset_perc:87.08%
allocator_allocated:1709352
allocator_active:1982464
allocator_resident:4812800
total_system_memory:13294940160
total_system_memory_human:12.38G
used_memory_lua:32768
used_memory_lua_human:32.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.16
allocator_frag_bytes:273112
allocator_rss_ratio:2.43
allocator_rss_bytes:2830336
rss_overhead_ratio:4.73
rss_overhead_bytes:17928192
mem_fragmentation_ratio:17.88
mem_fragmentation_bytes:21469184
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:41056
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:545
rdb_bgsave_in_progress:0
rdb_last_save_time:1681829368
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:2
total_commands_processed:1144
instantaneous_ops_per_sec:48
total_net_input_bytes:87539
total_net_output_bytes:12555
instantaneous_input_kbps:3.49
instantaneous_output_kbps:3.44
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:544
keyspace_misses:1
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:2
dump_payload_sanitizations:0
total_reads_processed:49
total_writes_processed:48
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:37ed9bfe9b457b35026f065324df615f9fd96f21
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.021503
used_cpu_user:0.053758
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
used_cpu_sys_main_thread:0.020846
used_cpu_user_main_thread:0.052116

# Modules
module:name=timeseries,ver=10617,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=ReJSON,ver=20200,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
module:name=graph,ver=20820,api=1,filters=0,usedby=[],using=[ReJSON],options=[]
module:name=search,ver=20415,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=bf,ver=20218,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_echo:calls=2,usec=45,usec_per_call=22.50,rejected_calls=0,failed_calls=0
cmdstat_FT.CURSOR:calls=17,usec=324,usec_per_call=19.06,rejected_calls=0,failed_calls=0
cmdstat_info:calls=4,usec=139,usec_per_call=34.75,rejected_calls=0,failed_calls=0
cmdstat_select:calls=565,usec=499,usec_per_call=0.88,rejected_calls=0,failed_calls=0
cmdstat_cluster:calls=1,usec=2,usec_per_call=2.00,rejected_calls=0,failed_calls=1
cmdstat_subscribe:calls=1,usec=9,usec_per_call=9.00,rejected_calls=0,failed_calls=0
cmdstat_get:calls=1,usec=11,usec_per_call=11.00,rejected_calls=0,failed_calls=0
cmdstat_FT.AGGREGATE:calls=3,usec=227,usec_per_call=75.67,rejected_calls=0,failed_calls=0
cmdstat_config:calls=3,usec=58,usec_per_call=19.33,rejected_calls=0,failed_calls=0
cmdstat_client:calls=2,usec=5,usec_per_call=2.50,rejected_calls=0,failed_calls=0
cmdstat_json.set:calls=544,usec=11965,usec_per_call=21.99,rejected_calls=0,failed_calls=0
cmdstat_FT.CREATE:calls=1,usec=227,usec_per_call=227.00,rejected_calls=0,failed_calls=0

# Errorstats
errorstat_ERR:count=2

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=544,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=11 addr=172.17.0.1:51024 laddr=172.17.0.2:6379 fd=12 name=BLG2A-V1-BB0562 age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=110 qbuf-free=40844 argv-mem=45 obl=9 oll=2 omem=20544 tot-mem=82077 events=r cmd=FT.CURSOR user=default redir=-1
id=12 addr=172.17.0.1:51026 laddr=172.17.0.2:6379 fd=13 name=BLG2A-V1-BB0562 age=0 idle=0 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20504 events=r cmd=subscribe user=default redir=-1

------ CURRENT CLIENT INFO ------
id=11 addr=172.17.0.1:51024 laddr=172.17.0.2:6379 fd=12 name=BLG2A-V1-BB0562 age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=110 qbuf-free=40844 argv-mem=45 obl=9 oll=2 omem=20544 tot-mem=82077 events=r cmd=FT.CURSOR user=default redir=-1
argv[0]: 'FT.CURSOR'
argv[1]: 'READ'
argv[2]: 'NumberTestIndex'
argv[3]: '1594252602'
argv[4]: 'COUNT'
argv[5]: '16'

------ MODULES INFO OUTPUT ------
# ReJSON_trace
ReJSON_trace:   0: redis_module::base_info_func
   1: rejson::__info_func
   2: modulesCollectInfo
             at /__w/redis-stack/redis-stack/redis/src/module.c:7100:9
   3: logModulesInfo
             at /__w/redis-stack/redis-stack/redis/src/debug.c:1598:22
   4: printCrashReport
             at /__w/redis-stack/redis-stack/redis/src/debug.c:1849:5
   5: sigsegvHandler
             at /__w/redis-stack/redis-stack/redis/src/debug.c:1831:5
   6: <unknown>
   7: readNumeric
   8: IR_Read
   9: UI_ReadSorted
  10: rpidxNext
  11: sendChunk
  12: runCursor
  13: RSCursorCommand
  14: RedisModuleCommandDispatcher
             at /__w/redis-stack/redis-stack/redis/src/module.c:695:5
  15: call
             at /__w/redis-stack/redis-stack/redis/src/server.c:3744:5
  16: processCommand
             at /__w/redis-stack/redis-stack/redis/src/server.c:4291:9
  17: processCommandAndResetClient
             at /__w/redis-stack/redis-stack/redis/src/networking.c:2102:9
  18: processInputBuffer
             at /__w/redis-stack/redis-stack/redis/src/networking.c:2203:17
  19: callHandler
             at /__w/redis-stack/redis-stack/redis/src/connhelpers.h:79:18
      connSocketEventHandler
             at /__w/redis-stack/redis-stack/redis/src/connection.c:295:14
  20: aeProcessEvents
             at /__w/redis-stack/redis-stack/redis/src/ae.c:427:17
  21: aeMain
             at /__w/redis-stack/redis-stack/redis/src/ae.c:487:9
  22: main
             at /__w/redis-stack/redis-stack/redis/src/server.c:6456:5
  23: __libc_start_main
  24: _start


# graph_executing commands

# search_version
search_RedisSearch_version:6.2.7

# search_index
search_number_of_indexes:1

# search_fields_statistics
search_fields_numeric:Numeric=1
search_fields_tag:Tag=1

# search_runtime_configurations
search_concurrent_mode:OFF
search_enableGC:ON
search_minimal_term_prefix:2
search_maximal_prefix_expansions:200
search_query_timeout_ms:500
search_timeout_policy:return
search_cursor_read_size:1000
search_cursor_max_idle_time:300000
search_max_doc_table_size:1000000
search_max_search_results:10000
search_max_aggregate_results:10000
search_search_pool_size:20
search_index_pool_size:8
search_gc_scan_size:100
search_min_phonetic_term_length:3

------ FAST MEMORY TEST ------
9:M 18 Apr 2023 14:49:58.943 # Bio thread for job type #0 terminated
9:M 18 Apr 2023 14:49:58.943 # Bio thread for job type #1 terminated
9:M 18 Apr 2023 14:49:58.943 # Bio thread for job type #2 terminated
*** Preparing to test memory region 55fcb5845000 (2281472 bytes)
*** Preparing to test memory region 55fcb7652000 (405504 bytes)
*** Preparing to test memory region 7f0d98631000 (3670016 bytes)
*** Preparing to test memory region 7f0d98f02000 (3145728 bytes)
*** Preparing to test memory region 7f0d9a060000 (2621440 bytes)
*** Preparing to test memory region 7f0d9a2e1000 (8388608 bytes)
*** Preparing to test memory region 7f0d9aae2000 (8388608 bytes)
*** Preparing to test memory region 7f0d9b2e3000 (8388608 bytes)
*** Preparing to test memory region 7f0d9bae4000 (8388608 bytes)
*** Preparing to test memory region 7f0d9c483000 (8388608 bytes)
*** Preparing to test memory region 7f0d9cc84000 (8388608 bytes)
*** Preparing to test memory region 7f0d9d663000 (12288 bytes)
*** Preparing to test memory region 7f0d9d6df000 (4096 bytes)
*** Preparing to test memory region 7f0d9d6e1000 (8388608 bytes)
*** Preparing to test memory region 7f0d9dee2000 (8388608 bytes)
*** Preparing to test memory region 7f0d9e6e3000 (8388608 bytes)
*** Preparing to test memory region 7f0d9eee4000 (8388608 bytes)
*** Preparing to test memory region 7f0d9f6e5000 (8388608 bytes)
*** Preparing to test memory region 7f0d9fee6000 (8388608 bytes)
*** Preparing to test memory region 7f0da06e7000 (8388608 bytes)
*** Preparing to test memory region 7f0da0ee8000 (8388608 bytes)
*** Preparing to test memory region 7f0da16e9000 (8388608 bytes)
*** Preparing to test memory region 7f0da1eea000 (8388608 bytes)
*** Preparing to test memory region 7f0da26eb000 (8388608 bytes)
*** Preparing to test memory region 7f0da45a1000 (12288 bytes)
*** Preparing to test memory region 7f0da45a5000 (8388608 bytes)
*** Preparing to test memory region 7f0da4da6000 (8388608 bytes)
*** Preparing to test memory region 7f0da59f9000 (28672 bytes)
*** Preparing to test memory region 7f0da5a00000 (8388608 bytes)
*** Preparing to test memory region 7f0da627a000 (24576 bytes)
*** Preparing to test memory region 7f0da646e000 (16384 bytes)
*** Preparing to test memory region 7f0da6491000 (16384 bytes)
*** Preparing to test memory region 7f0da6767000 (16384 bytes)
*** Preparing to test memory region 7f0da6953000 (8192 bytes)
*** Preparing to test memory region 7f0da6986000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: (null) (base: (nil))
Module: /opt/redis-stack/lib/redisearch.so (base 0x7f0da55a6000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=(nil) -D -b binary -m i386:x86-64 /tmp/dump.bin
------

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/redis/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

Segmentation fault 
```

Note: I use [NRediSearch 2.2.79](https://www.nuget.org/packages/NRediSearch/2.2.79) to setup the schema and run aggregations. But, end result does not change even if I run the aggregations manually by calling `FT.AGGREGATE ...` via `ExecuteAsync`.

**Comment by oshadmi** [comment]
Could be related to #2962
Which was fixed in [v2.4.16](https://github.com/RediSearch/RediSearch/releases/tag/v2.4.16)
Available with image redis/redis-stack:6.2.4-v4

**Comment by zahirtezcan-bugs** [comment]
I forgot to mention that newer versions does not cause the issue because it is not possible to iterate the cursor.

My reproduction code also contains a tag aggregation. If enabled via changing the code, tag aggregation never causes the fault. Text queries does not cause the fault either. So, this is directly related to numeric aggregations.

**Comment by zahirtezcan-bugs** [comment]
Just tested to use hash-based index with `HSET` instead of JSON-based index with `JSON.SET`, redis still crashes. Also crash happens if I use `FT.ADD` command ([undocumented?](https://redis.io/commands/)) with hash-based index.

Here is the updated reproduction code with local git management and added each implementation change as a different branch:
[RedisNumericCrashRepro-230419.zip](https://github.com/RediSearch/RediSearch/files/11270542/RedisNumericCrashRepro-230419.zip)
