### ISSUE TITLE
Redis hangs indefinitely after 5-6 hours of embeddings stream searches and indexing

### ISSUE THREAD

**Issue by Fikavec** [RediSearch/RediSearch#4186]
**Describe the bug**
I tried to use the docker image (redis/redis-stack-server:latest) or compile redis-redisearch myself from the git sources in Ubuntu Server 22.04. After 5-6 hours of work (~1 million 384-dimension embeddings indexed, Redis usinng near 5-6 Gb Ram ) in both services the redis connection freezes and stops responding, the redis-cli waits endlessly and does not connect as well as python client. The CPU is not busy and there is plenty (more than 50 GB)  of free RAM. Redis rdp disabled by setting save "" in config file, other settings by default. After restarting Redis service the situation is repeated repeatedly on different embeddings streams.
  - A message template appears in the docker logs every 30 seconds:
[current date time] * Module fork exited pid: [INCREASED NUMBER], retcode: 0, bysignal: 0

Code looks like:
```python
# !docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest
# !pip install -U redis

import redis
from redis.commands.search.field import TagField, VectorField
from redis.commands.search.indexDefinition import IndexDefinition, IndexType
from redis.commands.search.query import Query

redis_connection = redis.Redis(host="127.0.0.1", port=6379, decode_responses=True)

INDEX_NAME = "index" # Vector Index Name
DOC_PREFIX = "doc:"  # RediSearch Key Prefix for the Index

###
# create the index
###
# schema
schema = (
    VectorField("vector",                  # Vector Field Name
        "FLAT", {                          # Vector Index Type: FLAT or HNSW
            "TYPE": "FLOAT32",             # FLOAT32 or FLOAT64
            "DIM": 384,                    # Number of Vector Dimensions
            "DISTANCE_METRIC": "IP",   # Vector Search Distance Metric
        }
    ),
)
# index Definition
definition = IndexDefinition(prefix=[DOC_PREFIX], index_type=IndexType.HASH)
# create Index
redis_connection.ft(INDEX_NAME).create_index(fields=schema, definition=definition)


###
# Main loop with infinite texts stream
###
import numpy as np

query = (
    Query("(*)=>[KNN 2 @vector $vector as score]")
     .sort_by("score")
     .return_fields("id", "score")
     .paging(0, 2)
     .dialect(2)
)

for _id, text in enumerate(infinite_texts_stream):
    embedding = encode_text_to_embedding([text])[0].numpy().astype(np.float32).tobytes()
    
    for doc in redis_connection.ft(INDEX_NAME).search(query, {"vector":embedding}).docs:
        # Work with founed similar items
        print(doc)
        
    # HSET
    redis_connection.hset(f"{DOC_PREFIX}{_id}", mapping={"vector":embedding})    
```

What could be the problem? How, besides the logs, can I diagnose the condition of the Redis if i have not been connected to it? 

-----
<search> Redis version found by RedisSearch : 7.2.3 - oss
<search> RediSearch version 2.8.9 (Git=HEAD-58db69da)

**Comment by meiravgri** [comment]
Hi, thank you for reporting this issue.
We're going to delve into it and will keep you informed. If additional information is needed, we'll reach out to you.

**Comment by meiravgri** [comment]
Regarding the message in the log, it's normal.

**Comment by alonre24** [comment]
Hi @Fikavec ,
Why did you close this issue?

**Comment by Fikavec** [comment]
> Hi @Fikavec , Why did you close this issue?

Hi @alonre24, I tested same workload on [redis-stack-server/latest](https://hub.docker.com/layers/redis/redis-stack-server/latest/images/sha256-e13c8531d1c16b58b822182933866013d4d32353a7790557f8972132e8555d1b?context=explore) image with RediSearch 2.8.11 and bug still here, but without messages in docker logs every 30 seconds and one cpu core loaded by redis process near 30%. it is impossible to connect to redis even through the redis-cli from the docker container, there are no unusual messages in the logs. Since I reported the problem and can't diagnose the cause and help with its solution, so I closed the issue.

**Comment by alonre24** [comment]
I understand and thank you for the update. We will leave this ticket open while we investigate what is causing this issue. Let us know if you have further insights.

**Comment by alonre24** [comment]
When I try to reproduce, after loading 1M vectors the memory consumption by redis is ~3.3GB (not 5-6). Does your schema consist of `FLAT` vector field only as seen in the code snippet above?
Also, can you try running again after executing `config set loglevel debug` command in redis-cli? Then, please share the shard log, hopefully, it will contain some helpful information.

**Comment by Fikavec** [comment]
> When I try to reproduce, after loading 1M vectors the memory consumption by redis is ~3.3GB (not 5-6). Does your schema consist of `FLAT` vector field only as seen in the code snippet above? 

Did you have a problem with the connection during reproduction? My full scheme also contains a TagField and a NumericField with a date in epoch seconds and HNSW vector index type. The memory consumption of an index (even with 30% for HNSW) also surprised me, but my problem is a connection hang. I have enabled loglevel debug and will try to wait for the connection to hang - if this happens, I will show what was in the log.

At the stage of creating the index, I faced the question of the necessary RAM. Indeed, 1 million float32 vectors of dimension 384 consumes (1000000*32*384)/8/1024/1024/1024 = 1.43 GB of memory, but after setting maxmemory to 8GB, creating an index with a capacity of 1000000 give my an error: "ResponseError: Vector index initial capacity 1000000 exceeded server limit (385015 with the given parameters)" - but why is this happening, because 8GB is 5.5+ times more than it needs to store a million vectors?
```python
# docker pull redis/redis-stack-server:latest
# docker run -d --name redis-stack-server -p 6379:6379 -p 8001:8001 redis/redis-stack-server:latest

# Python 3.11.5 on Windows
# pip install "redis[hiredis]" 
import redis
from redis.commands.search.field import TagField, VectorField, NumericField
from redis.commands.search.indexDefinition import IndexDefinition, IndexType
from redis.commands.search.query import Query

r = redis.Redis(host="127.0.0.1", port=6379, db=0, decode_responses=True)

r.config_set('maxmemory','8GB')
r.config_set('save','')
r.config_set('loglevel','debug')

print(r.config_get("maxmemory"))

schema = (
    TagField("task"),
    TagField("name"),
    NumericField("date"),
    VectorField("vector",                  
        "HNSW", {                          
            "TYPE": "FLOAT32",             
            "DIM": 384,                    
            "DISTANCE_METRIC": "IP",
            "M": 64,
            "EF_CONSTRUCTION": 256,
            "INITIAL_CAP": 1000000,
        }
    ),
)

definition = IndexDefinition(prefix=[""])

r.ft('new_index').create_index(fields=schema, definition=definition)

# output:
# {'maxmemory': '8589934592'}
# ... ResponseError: Vector index initial capacity 1000000 exceeded server limit (250991 with the given parameters)
```
If I reduce INITIAL_CAP to 100,000, then the index is created and after adding a million vectors to it takes about  5-6 Gb of Ram, that is, they fit into 8GB and the index should have been created with such settings - is this the regular behavior of redis?

**Comment by alonre24** [comment]
Regarding the memory limit - yes, we currently enforce that the estimated initial size of the index is no more than 10% of the memory limit. This is configurable and can be changed via [VSS_MAX_RESIZE](https://redis.io/docs/interact/search-and-query/basic-constructs/configuration-parameters/#vss_max_resize) configuration.

I used the schema you provided and added random numeric values and tags (along with the random vectors), and I still hadn't managed to reproduce the connection hang after 1M adding 1M documents and running queries. Are you doing updates on the data as well? 
Let me know if you manage to reproduce after setting the log level to debug and attach please the detailed log. 
Thanks!

**Comment by Fikavec** [comment]
Thanks, it became clear why it was not possible to create an index with a large INITIAL_CAP (in my case, there are a lot of one search+one indexing operations, this led to a very frequent message in log like "Updating HNSW index capacity from 1092608 to 1093632"), but it is still unclear why a million vectors take 5-6GB instead of 2GB ( = 1.43 GB vectors + 0.42 GB as 30% HNSW index ) RAM.

Is the docker container log a "detailed log" or does it need to be searched on the container's disk (find / -name "redis*" did not give me any results with .log extension)? The Docker container log looks very simple - repeating loops:
```
<search> Thread-0 is running iteration
Module fork started pid: 849
Killing running module fork child: 849
<search> All threads are idle
DB 0: 1161574 keys (0 volatile) in 2097152 slots HT.
1 clients connected (0 replicas), 6358570736 bytes in use
DB 0: 1161682 keys (0 volatile) in 2097152 slots HT.
1 clients connected (0 replicas), 6358870080 bytes in use
DB 0: 1161797 keys (0 volatile) in 2097152 slots HT.
1 clients connected (0 replicas), 6359169296 bytes in use
<search> Thread-0 is running iteration
<search> All threads are idle
DB 0: 1161879 keys (0 volatile) in 2097152 slots HT.
1 clients connected (0 replicas), 6359357656 bytes in use
```
After 11 hours of work and this last message in docker log redis connection begins to hang again (redis-cli can't connect - waits infinitely and not rejected or terminated; python can't connect by timeout; the docker container still working and I can run bash commands in it, the CPU is not busy, there is a lot of free RAM).
I don't do any data updates, but after 1000 cycles (search+hset) I am deleting outdated old keys with data. In the beginning, I implemented deletion via ttl in redis (redis_connection.hset(f"{DOC_PREFIX}{_id}"...) and then redis_connection.expire(f"{DOC_PREFIX}{_id}", 24*3600) ), but the connection was hanging. I rewrote the deletion to searching for outdated ids by its timestamp and deleting them by redis_connection.delete(*list_of_keys), but such a deletion of a couple of thousand keys could take more than 10 minutes and there was too much downtime processing the data stream (so long that I just couldn't wait for the hangup). I rewrote the deletion to redis_connection.unlink(*list_of_keys), faced with a limit on deleting more than 10,000 keys at once and, as a result, I do a search with .paging(0, 5000) then redis_connection.unlink(*this 5000 keys), while search results is not empty - it works fast. But no matter what I do, the connection hangs sooner or later. I do not exclude that the cause of the problem is deletion (since the delete operation is performed for a long time, it is clear that this is a complex process - from rebuilding the HNSW index, to erasing keys and clearing memory) - before choosing redis, I was doing stress testing it on synthetic data (but without deletions by ttl, without pauses and uneven load and other difficult-to-synthesize properties of a real stream) and it worked stably for days at a speed of 20-25 million cycles (one embedding search+one embedding hset) per day.

**Comment by alonre24** [comment]
1. Vectors in Redis are stored twice today - in Redis keyspace (as part of the hash) and in the vector index + HNSW and other indexed types consumption leads to the 5-6 GB memory consumption that you see. 
2. The detailed log (in debug mode) is the same shard log (from which you attached the snippet) 
3. Using the TTL should have worked. The workarounds that you implemented are fine, but to find the root cause for the hang, let's try to reproduce with the TTL.
4. I know that the logs in debug mode are heavy, but can you attach the entire log from the last ~minute before the hang? It may help us with the investigation.

Thanks!

**Comment by Fikavec** [comment]
> Vectors in Redis are stored twice today

Is it also true for vectors stored as fields in JSON documents? Is there an option to not store vectors at all if I only need to index and search through them and never need to return them? In the Elasticsearch mapping, this can be done by "_source": { "excludes": ["vector_field"]}.

> Using the TTL should have worked.

I wrote and attached a [redis_hang_test.zip](https://github.com/RediSearch/RediSearch/files/14321766/redis_hang_test.zip) script (with keys expire) very similar to my workload, which may be useful for stress testing. After 10 hours of its operation, there were no problems, I will try to run it on the server and wait a little longer. 

> can you attach the entire log from the last ~minute

I had previously written what was in the log in the last few minutes. The size of the log turned out to be about 1 megabyte, and the mentioned lines were repeated in it almost all the time. Unfortunately, the server access tools do not allow me to copy the log file (copying files and ctrl-c/v does not work), and there was no hang outside the server during non-round-the-clock of testing.

> This is configurable and can be changed via [VSS_MAX_RESIZE](https://redis.io/docs/interact/search-and-query/basic-constructs/configuration-parameters/#vss_max_resize) configuration.

Maybe add this hint into the current error message `ResponseError: Vector index initial capacity 1000000 exceeded server limit (250991 with the given parameters)`? In my case, the entire redis is worth using only because of RediSearch vector search and I would like to have the maximum amount of memory for RediSearch, except for the minimum required by Redis itself.


P.S. If you are interested, then in this way of using RediSearch (temporary vector cache without persistence with realtime search on streamed data, like attached script) it is about 7-10 times faster than Elasticsearch, Milvis, Qdrant, Weaviate, Vespa  according to my tests (their performance is within avg. 2-3 million cycles per day vs avg. 25 millions in RediSearch, even if you run it on a ram disk like `docker run --rm -it --network=host --mount type=tmpfs,dst=/qdrant/storage qdrant/qdrant:latest`), because in my use case they architecturally have too much overhead for persistence and real time search: on-disk Write Ahead Logging (wal/translog), on-disk 1 document segments-merges to make the document visible in the search (lucene need commit for document visible), search results caching and so on. Chromadb is also fast enough in this case (avg. 17 million cycles per day), but it [does not have an index by fields](https://github.com/chroma-core/chroma/issues/1394) and is simply not able to work with millions of vectors with field filters (without fields filters, vector search alone can withstand tens of millions of vectors). RediSearch works with a database of 50+ million vectors. HNSWlib gives me avg. 32 million cycles per day, but it's also without filtering by fields (which is not implemented in hnswlib), it's built right into the code and there's no data transfer overhead, so it seems to me that 25 million RediSearch is (HNSWlib - data transfer overhead), that is, close to the maximum performance per 1 processor core. 


Thanks!

**Comment by Fikavec** [comment]
The previously attached script [redis_hang_test.zip](https://github.com/RediSearch/RediSearch/files/14321766/redis_hang_test.zip) also caused a connection hang on server. It can be used to reproduce and test the problem.

**Comment by alonre24** [comment]
Thank you for all the insights and the detailed information that you share!
It really helps us to learn and improve.
Once you get the server hanging, please send signal 11 to the process. It
should cause the server to write a crash report to the log from which we
can infer what's going on (please attach the report).
Thanks

בתאריך יום ה׳, 22 בפבר׳ 2024, 23:41, מאת Fikavec ***@***.***

**Comment by alonre24** [comment]
Update - I managed to reproduce locally and found the hang. Currently investigating and trying to understand what causing it. I Will update here once I have more information (and hopefully a fix)

**Comment by alonre24** [comment]
The problem was found and a fix was merged to master. You can try again with our updated master branch. Thank you!

**Comment by Fikavec** [comment]
Still hangs. I tested same real and test workload on docker redis-stack-server/latest image with Redis 7.2.4 RediSearch 2.8.12 (Git=2.8-32fdaca).

**Comment by alonre24** [comment]
Right, bacause it is not available in redis-stack-server/latest image yet, only in redisearch *master* branch. It will be availble in redis-stack latest within few weeks

**Comment by Fikavec** [comment]
16 days of round-the-clock RediSearch 2.8.13 (Git=2.8-c1535c6) testing - no problems, the bug has been fixed, thanks!
