### ISSUE TITLE
[BUG] trapped into a dead cycle in Wildcard_MatchChar

### ISSUE THREAD

**Issue by 1000happiness** [RediSearch/RediSearch#5895]
**Describe the bug**
The RedisSearch Module will trap into a dead cycle in Wildcard_MatchChar when the input pattern and str are in a special schema.

**To Reproduce**
1. add an json object：`json.set test/3 $ '{"comment": "456a\\*456"}'`
2. add an index on key with 'test/' prefix: `ft.create index:test ON JSON PREFIX 1 test/ SCHEMA $.comment as comment TEXT`
3. do search on the index: `ft.search index:test "@comment:w'*abc123*'" DIALECT 2 VERBATIM`

If the value which is searched is like '...a*...' and the pattern is like '*a....'(the character 'a' can also be other characters), the redis will be trapped into dead loop.

**Expected behavior**
a normal search. no dead loop

**Screenshots**
![Image](https://github.com/user-attachments/assets/74c07b8b-31e2-4eb7-92f9-d702d51a46d6)
(redis-cli is blocked and I interrupt it)

**Environment (please complete the following information):**
 - OS: Centos7.9
 - x86_64
 - v2.6.9（I try this in the newest version, it also exist）

**Additional context**
When use gdb to watch what happened in the module, I find it trapped in Wildcard_MatchChar function.
The reason of this bug is here.

`if ((str_end != str_itr) && (c == *str_itr || c == '?'))`

![Image](https://github.com/user-attachments/assets/dce78564-eadf-4b2e-aba7-ee9f2f8911fc)

When compare c(a character in patern) with target str, it will be wrong if there is a '*' character in target str.

**Comment by 1000happiness** [comment]
The '*' character will be used as decollator by default, so it is hard to find.

**Comment by kei-nan** [comment]
Hi @1000happiness,
I think this was fixed in https://github.com/RediSearch/RediSearch/pull/4932.
Please check the latest 2.6 release, it should be fixed there.

**Comment by 1000happiness** [comment]
@kei-nan I retry this in the 2.6.26.(using https://github.com/redis-stack/redis-stack/releases/tag/v6.2.6-v19) It happens again.
It seems that another bug still exists.

**Comment by 1000happiness** [comment]
![Image](https://github.com/user-attachments/assets/e2ba44f7-7979-4510-9f77-04e645d08936)

![Image](https://github.com/user-attachments/assets/330a0d0e-c131-4e34-814e-27d5b82d2a0d)

**Comment by raz-mon** [comment]
@1000happiness This is essentially the same bug, but in this case for the `TEXT` field, in which the escaping is needed (probably thus missed in the last fix since it was not the case there). So it is not in `Wildcard_MatchChar`, but in `Wildcard_MatchRune`.
The fix should be similar.
Thank you for surfacing this issue! We will handle it ASAP.
