### ISSUE TITLE
nil values returned for non-existent fields when sorting

### ISSUE THREAD

**Issue by mmasouras** [RediSearch/RediSearch#919]
RS returns a nil value when I am sorting and the document doesn't have that field. I am investigating further to understand if that happens in all cases or there are special circumstances that lead to this. 

The document p:734802 does NOT have a field "price". Here I dump the entire document, add it to search, and then search for it with sorting.

```
127.0.0.1:6379> HGETALL p:734802
 1) "imgurlsmall"
 2) "https://storage.googleapis.com/lwimg/mh/l/20190615/5bc8cded36741bf5e2bce5fad41fe6d4.png"
 3) "feed"
 4) "f:themotorcafenew"
 5) "_t"
 6) "1560589933"
 7) "title"
 8) "2019 MULTISTRADA 1260S TOURING - Ducati"
 9) "tags"
10) "vm:77,w:couchride:t:europe,vm:146,w:couchride:t:adventure423,vm:162,vm:191,w:couchride:t:dealer,w:couchride:t:new,t:image,w:couchride:t:hasvin,w:couchride:t:touring,w:couchride:t:ducati,w:couchride:t:multistrada,w:couchride:t:multistrada1260,w:couchride:t:multistrada1260s,w:couchride,f:themotorcafenew,cf:d:729,cf:m:ari,CA"
11) "location"
12) "Sunnyvale, CA"
13) "geo"
14) "-122.0363496 37.36883"
15) "created"
16) "2019-06-15 09:12:13"
17) "ctitle"
18) "2019 MULTISTRADA 1260S TOURING Ducati"
19) "mpid"
20) "cf:m:ari"
21) "ct"
22) "l"
23) "year"
24) "2019"
25) "imgurl"
26) "https://cdnmedia.endeavorsuite.com/images/ThumbGenerator/Thumb.aspx?img=https%3a%2f%2fcdnmedia.endeavorsuite.com%2fimages%2fassets%2fimg%2fno-image-if.png&mw=350&mh=200&f=1&fz=1"
27) "vin"
28) "zdmaaekw1kb007485"
29) "psd"
30) "ari"
31) "is"
32) "\n\x0f\xeb@\x93%\x12\x17[\xda#\xdf\x97F\a\x05"
33) "mileage"
34) "000003"
35) "ssc"
36) "2272"
37) "st"
38) "CA"
39) "did"
40) "cf:d:729"
41) "ss"
42) "88329"
43) "url"
44) "https://www.themotorcafe.com/inventory/2019-ducati-multistrada-1260s-touring-sunnyvale-ca-94087-2643036i"
45) "imgurllarge"
46) "https://storage.googleapis.com/lwimg/mh/l/20190615/105ec8b4ff94206ae43fd3fd9619aa8f.png"
47) "ssf"
48) "9399"


127.0.0.1:6379> FT.ADDHASH il1 p:734802 1.0 REPLACE
OK

127.0.0.1:6379> "FT.SEARCH" "il1" "@ctitle:multistrada* 1260s* @tags:{w\\:couchride\\:t\\:adventure423} @year:[2019 inf] @geo:[-122.0363496 37.36883 10 mi]" "LIMIT" "0" "20" "SORTBY" "price" "DESC"
1) (integer) 1
2) "p:734802"
3)  1) price                           \<----------- HERE
    2) (nil)                                \<----------- HERE
    3) imgurlsmall
    4) "https://storage.googleapis.com/lwimg/mh/l/20190615/5bc8cded36741bf5e2bce5fad41fe6d4.png"
    5) feed
    ... remaining fields .....
```

Let's try to explicitly "delete" this field:

```
127.0.0.1:6379> HDEL p:734802 price
(integer) 0
127.0.0.1:6379> FT.ADDHASH il1 p:734802 1.0 REPLACE
OK
127.0.0.1:6379> "FT.SEARCH" "il1" "@ctitle:multistrada* 1260s* @tags:{w\\:couchride\\:t\\:adventure423} @year:[2019 inf] @geo:[-122.0363496 37.36883 10 mi]" "LIMIT" "0" "20" "SORTBY" "price" "DESC"
1) (integer) 1
2) "p:734802"
3)  1) price
    2) (nil)
    3) imgurlsmall
   ..... more .... 
```

"price" is still there in the results. If I ask for specific fields with RETURN, then it's ok.

This is causing the go library I use to parse the result to fail:
https://github.com/gomodule/redigo/issues/437

**Comment by mnunberg** [comment]
what version are you using?

**Comment by mnunberg** [comment]
also does this happen for fields that dont exist at all (w/o addhash...replace and del)

**Comment by mmasouras** [comment]
I am using this version in production:
RediSearch version 1.4.2 (Git=v1.4.2-255-gf947fd74)

I have not tried it with the latest version because I can't get it to run: https://github.com/RediSearch/RediSearch/issues/888 

It's ok to leave this issue open/unattended until we figure the major crashing problem out and then I 'll try it again and see if it persists. Also yes, this field is sortable.

**Comment by mmasouras** [comment]
Hi, do you think you 'll be able to take a look at this now?

**Comment by mnunberg** [comment]
@mmasouras #888 is fixed, so give a go theere

**Comment by mmasouras** [comment]
I still get a core dump :( 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
27649:M 07 Oct 2019 12:01:02.904 # ------------------------------------------------
27649:M 07 Oct 2019 12:01:02.904 # !!! Software Failure. Press left mouse button to continue
27649:M 07 Oct 2019 12:01:02.905 # Guru Meditation: Redis aborting for OUT OF MEMORY #server.c:3893
27649:M 07 Oct 2019 12:01:02.905 # (forcing SIGSEGV in order to print the stack trace)
27649:M 07 Oct 2019 12:01:02.905 # ------------------------------------------------
27649:M 07 Oct 2019 12:01:02.906 # Redis 5.0.5 crashed by signal: 11
27649:M 07 Oct 2019 12:01:02.906 # Crashed running the instruction at: 0x105a5d80e
27649:M 07 Oct 2019 12:01:02.906 # Accessing address: 0xffffffffffffffff
27649:M 07 Oct 2019 12:01:02.906 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
0   redis-server                        0x0000000105a5d80e _serverPanic + 334

Backtrace:
0   redis-server                        0x0000000105a5f8de logStackTrace + 110
1   redis-server                        0x0000000105a5fcad sigsegvHandler + 253
2   libsystem_platform.dylib            0x00007fff5dd6cb5d _sigtramp + 29
3   ???                                 0x924386bffd580052 0x0 + 10539415712124371026
4   redis-server                        0x0000000105a14357 redisOutOfMemoryHandler + 55
5   redis-server                        0x0000000105a17e10 zmalloc + 32
6   redisearch.so                       0x0000000105c6ac10 FGC_recvInvIdx + 320
7   redisearch.so                       0x0000000105c6932b FGC_parentHandleFromChild + 267
8   redisearch.so                       0x0000000105c6a59c periodicCb + 524
9   redisearch.so                       0x0000000105c6dc6b GCContext_PeriodicCallback + 59
10  redisearch.so                       0x0000000105ccc24c rmutilTimer_Loop + 204
11  libsystem_pthread.dylib             0x00007fff5dd752eb _pthread_body + 126
12  libsystem_pthread.dylib             0x00007fff5dd78249 _pthread_start + 66
13  libsystem_pthread.dylib             0x00007fff5dd7440d thread_start + 13

**Comment by mmasouras** [comment]
27649:M 07 Oct 2019 12:00:25.839 # Server initialized
27649:M 07 Oct 2019 12:00:25.842 * <ft> RediSearch version 99.99.99 (Git=v1.6.0-299-ga9b0a50c)
27649:M 07 Oct 2019 12:00:25.842 * <ft> Low level api version 1 initialized successfully
27649:M 07 Oct 2019 12:00:25.843 * <ft> concurrency: ON, gc: ON, prefix min length: 1, prefix max expansions: 200, query timeout (ms): 10000, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 10000000, search pool size: 20, index pool size: 8,
27649:M 07 Oct 2019 12:00:25.844 * <ft> Initialized thread pool!
27649:M 07 Oct 2019 12:00:25.844 * Module 'ft' loaded from /Users/michaelmasouras/src/redis-5.0.5/redisearch.so
27649:M 07 Oct 2019 12:01:02.714 * DB loaded from disk: 36.870 seconds
27649:M 07 Oct 2019 12:01:02.719 * Ready to accept connections
27649:M 07 Oct 2019 12:01:02.897 # Out Of Memory allocating 140636750889297 bytes!

**Comment by mmasouras** [comment]
I removed my rdb file completely and let the recplica do a full resync. That seemed to stop the core-dump from happening. 

However, the original problem (getting nil values back when sorting) is not addressed with the latest build.

**Comment by mnunberg** [comment]
Hrm, I still cannot replicate this behavior.. Can you send me your rdb again? (If you've sent it already, I apologize.. I am just now recovering)

**Comment by MeirShpilraien** [comment]
@mmasouras Can you pls check with v1.6.4 to verify that the crash has been fixed?

**Comment by mnunberg** [comment]
@mmasouras I'm based in Central Florida but my hours are all over the place  :)

**Comment by mmasouras** [comment]
Hi, I installed the latest version but unfortunately I still see the bug. 

16507:S 23 Oct 2019 17:44:43.657 * <ft> RediSearch version 1.6.4 (Git=v1.6.4)
16507:S 23 Oct 2019 17:44:43.657 * <ft> Low level api version 1 initialized successfully


127.0.0.1:6379> "FT.SEARCH" "il1" "@ctitle:vulcan* @tags:{w\\:couchride\\:t\\:bagger} @tags:{w\\:couchride} @geo:[-122.4325682 37.7561438 10 mi]" "LIMIT" "0" "20" "SORTBY" "price" "DESC"
1) (integer) 1
2) "p:563978"
3)  1) "price"
    2) (nil)                        <---------------
    3) "ss"
    4) "82286"
    5) "geo"
    6) "-122.4194155 37.7749295"
.....

127.0.0.1:6379> ft.info il1
 1) index_name
 2) il1
 3) index_options
 4) 1) "NOFREQS"
    2) "NOOFFSETS"
 5) fields
 6)  1) 1) ctitle
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
        6) NOSTEM
     2) 1) geo
        2) type
        3) GEO
     3) 1) _t
        2) type
        3) NUMERIC
        4) SORTABLE
     4) 1) tags
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
     5) 1) price
        2) type
        3) NUMERIC
        4) SORTABLE
     6) 1) year
        2) type
        3) NUMERIC
        4) SORTABLE
     7) 1) mileage
        2) type
        3) NUMERIC
        4) SORTABLE
     8) 1) _at
        2) type
        3) NUMERIC
     9) 1) st
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    10) 1) ss
        2) type
        3) NUMERIC
        4) SORTABLE
 7) num_docs
 8) "163351"
 9) max_doc_id
10) "113911819"
11) num_terms
12) "27775"
13) num_records
14) "1.8446744072303491e+19"
15) inverted_sz_mb
16) "17592186040376.945"
17) total_inverted_index_blocks
18) "1.8446744073709306e+19"
19) offset_vectors_sz_mb
20) "0"
21) doc_table_size_mb
22) "13.781818389892578"
23) sortable_values_size_mb
24) "18.697059631347656"
25) key_table_size_mb
26) "4.4246101379394531"
27) records_per_doc_avg
28) "112927034874041.48"
29) bytes_per_record_avg
30) "1"
31) offsets_per_term_avg
32) "0"
33) offset_bits_per_record_avg
34) "-nan"
35) gc_stats
36)  1) bytes_collected
     2) "0"
     3) total_ms_run
     4) "0"
     5) total_cycles
     6) "0"
     7) avarage_cycle_time_ms
     8) "-nan"
     9) last_run_time_ms
    10) "0"
    11) gc_numeric_trees_missed
    12) "0"
    13) gc_blocks_denied
    14) "0"
37) cursor_stats
38) 1) global_idle
    2) (integer) 0
    3) global_total
    4) (integer) 0
    5) index_capacity
    6) (integer) 128
    7) index_total
    8) (integer) 0

**Comment by mmasouras** [comment]
I will let you know if it crashes again. In the meantime, my build from a few days ago crashed again tonight.

redisearch crash (fatal):
https://github.com/RediSearch/RediSearch/issues/959

redis rdb save crash (non-fatal for main process)
https://github.com/antirez/redis/issues/6494

**Comment by mmasouras** [comment]
The rdb crash is now here https://github.com/RediSearch/RediSearch/issues/960

**Comment by MeirShpilraien** [comment]
Is this on 1.6.4? Pls specify versions on each issue you open.

**Comment by mmasouras** [comment]
This issue is about nil values returned. I pasted the latest response from redisearch above, along with the version number:
16507:S 23 Oct 2019 17:44:43.657 * RediSearch version 1.6.4 (Git=v1.6.4)

The crashes were happening with the previous version, I pasted it in the two issues:
RediSearch version 99.99.99 (Git=v1.6.0-331-g392fd654)

**Comment by mnunberg** [comment]
I’ll look with the rdb you provided

**Comment by mmasouras** [comment]
Thanks.

FYI, the crashes will not be easy to replicate - they happened after I had the server running for a few days:
https://github.com/antirez/redis/issues/6494#issuecomment-545552292

**Comment by MeirShpilraien** [comment]
@mnunberg there is also a crash in this ticket (not just the nil value return) and the crash look different then the other crashes you reported yesterday, I want to understand if this crash is solved on the new version (1.6.4)

**Comment by mmasouras** [comment]
The crash in this ticket does not seem to happen anymore. 

However, yesterday night I had two more crashes that seem similar to each other. I am pasting the stack traces here, would you like me to file a separate bug for those:


16507:S 23 Oct 2019 17:44:43.657 * <ft> RediSearch version 1.6.4 (Git=v1.6.4)


=== REDIS BUG REPORT START: Cut & paste starting from here ===
15234:C 24 Oct 2019 07:05:06.885 # Redis 5.0.6 crashed by signal: 11
15234:C 24 Oct 2019 07:05:06.886 # Crashed running the instruction at: 0x7fb70f493099
15234:C 24 Oct 2019 07:05:06.886 # Accessing address: (nil)
15234:C 24 Oct 2019 07:05:06.886 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/home/redis/redisearch.so(DocTable_Exists+0x49)[0x7fb70f493099]

Backtrace:
/usr/local/bin/redis-server *:6379(logStackTrace+0x5a)[0x55dc16eed73a]
/usr/local/bin/redis-server *:6379(sigsegvHandler+0xb1)[0x55dc16eedef1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fb711e6f890]
/home/redis/redisearch.so(DocTable_Exists+0x49)[0x7fb70f493099]
/home/redis/redisearch.so(IndexBlock_Repair+0x119)[0x7fb70f4a56e9]
/home/redis/redisearch.so(+0x4dc5a)[0x7fb70f498c5a]
/home/redis/redisearch.so(+0x4f680)[0x7fb70f49a680]
/home/redis/redisearch.so(+0x5113d)[0x7fb70f49c13d]
/home/redis/redisearch.so(+0xb4b40)[0x7fb70f4ffb40]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7fb711e646db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fb711b8d88f]




=== REDIS BUG REPORT START: Cut & paste starting from here ===
16507:S 24 Oct 2019 07:07:14.426 # Redis 5.0.6 crashed by signal: 11
16507:S 24 Oct 2019 07:07:14.427 # Crashed running the instruction at: 0x7fb70f493010
16507:S 24 Oct 2019 07:07:14.427 # Accessing address: (nil)
16507:S 24 Oct 2019 07:07:14.427 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/home/redis/redisearch.so(DocTable_Get+0x40)[0x7fb70f493010]

Backtrace:
/usr/local/bin/redis-server *:6379(logStackTrace+0x5a)[0x55dc16eed73a]
/usr/local/bin/redis-server *:6379(sigsegvHandler+0xb1)[0x55dc16eedef1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fb711e6f890]
/home/redis/redisearch.so(DocTable_Get+0x40)[0x7fb70f493010]
/home/redis/redisearch.so(+0x68028)[0x7fb70f4b3028]
/home/redis/redisearch.so(+0x684c1)[0x7fb70f4b34c1]
/home/redis/redisearch.so(+0x6859b)[0x7fb70f4b359b]
/home/redis/redisearch.so(+0x68348)[0x7fb70f4b3348]
/home/redis/redisearch.so(+0x75a94)[0x7fb70f4c0a94]
/home/redis/redisearch.so(AREQ_Execute+0x10)[0x7fb70f4c0f80]
/home/redis/redisearch.so(+0x76168)[0x7fb70f4c1168]
/usr/local/bin/redis-server *:6379(RedisModuleCommandDispatcher+0x68)[0x55dc16f1b508]
/usr/local/bin/redis-server *:6379(call+0xb5)[0x55dc16ea6e55]
/usr/local/bin/redis-server *:6379(processCommand+0x36f)[0x55dc16ea755f]
/usr/local/bin/redis-server *:6379(processInputBuffer+0x171)[0x55dc16eb8051]
/usr/local/bin/redis-server *:6379(aeProcessEvents+0x150)[0x55dc16ea0890]
/usr/local/bin/redis-server *:6379(aeMain+0x2b)[0x55dc16ea0c7b]
/usr/local/bin/redis-server *:6379(main+0x4f4)[0x55dc16e9d824]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fb711a8db97]
/usr/local/bin/redis-server *:6379(_start+0x2a)[0x55dc16e9da7a]

**Comment by mnunberg** [comment]
so back to the original issue.. it seems that the document itself has a 'nil' value for price, for some reason..

**Comment by mmasouras** [comment]
In case it helps:

127.0.0.1:6379> hget p:563978 price
(nil)

127.0.0.1:6379> hget p:563978 fielddoesnotexist
(nil)

**Comment by mnunberg** [comment]
@mmasouras What version was the rdb initially loaded with?

**Comment by mnunberg** [comment]
I think this has to do with an earlier version of search placing `NULL` inside the sorting table..

**Comment by mmasouras** [comment]
Well this RDB was first created by redis > 2 years ago and then I added redisearch about 18 months ago if that's what you are asking. 

This redis instance is a replica BTW, its master is still on
26827:M 18 Oct 2018 19:42:13.517 * <ft> RediSearch version 1.4.1 (Git=v1.4.1-rc2-3-gcd66d601)

**Comment by mnunberg** [comment]
So, the actual issue (at the head of this issue) is solved. I believe there are other issues for the crashes.

**Comment by mmasouras** [comment]
I tested this fix and it worked. Thank you.
